// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCebfUuUgGYQhxmowIQeh761uyXQPgqFBI',
    appId: '1:1051697319511:android:636c026973917cf2fa1d12',
    messagingSenderId: '1051697319511',
    projectId: 'chit-chat-1d955',
    storageBucket: 'chit-chat-1d955.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEJ8W0-BXg39osst8YT91MTZ1C1PLB0uo',
    appId: '1:1051697319511:ios:be4af449c5d47c7afa1d12',
    messagingSenderId: '1051697319511',
    projectId: 'chit-chat-1d955',
    storageBucket: 'chit-chat-1d955.firebasestorage.app',
    androidClientId: '1051697319511-pit713behbm8t3dnf5v85c89uv3br4j9.apps.googleusercontent.com',
    iosClientId: '1051697319511-8l7pht9uuu357g0oaueb93irma8ku6k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chitChat',
  );

}